# Generated by Django 5.1 on 2024-08-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('group', models.CharField(choices=[('Group 1', 'Group 1'), ('Group 2', 'Group 2'), ('Group 3', 'Group 3')], max_length=20)),
            ],
        ),
    ]
