# Generated by Django 5.1 on 2024-08-26 12:08

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputdata',
            name='nation_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inputdata',
            name='nation',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
